In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from kornia.utils.grid import create_meshgrid3d

c:\Users\huwki\AppData\Local\Programs\Python\Python39\lib\site-packages\kornia\augmentation\augmentation.py:1830: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  warnings.warn(


In [2]:
D = H = W = 8
coord_grids = create_meshgrid3d(D, H, W, False, dtype=torch.int32)
assert coord_grids.shape == torch.Size((1, D, H, W, 3))
coord_grids[0,0,0,0]
coord_grids[0,0,0,1]

c:\Users\huwki\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


tensor([0, 1, 0], dtype=torch.int32)

In [3]:
o = torch.tensor((-0.5, 0.5, 0.5), dtype=torch.float32)
d = F.normalize(torch.tensor([1,2,3], dtype=torch.float32), dim=0)

In [4]:
x = torch.tensor([3,4,5]).float()

In [5]:
F.normalize(x, dim=0)

tensor([0.4243, 0.5657, 0.7071])

In [6]:
x.norm() * F.normalize(x, dim=0)

tensor([3., 4., 5.])

In [8]:
i = torch.randn(3, 4)
i[:, 3]

tensor([ 2.0601,  1.1805, -1.1747])

In [9]:
import numpy as np
np.random.choice(5, 1)

array([4])